version: "3.7"

services:
  db:
    image: postgres:10.10
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ''
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
